
spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/desafio_btg}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    # hikari
    hikari:
      idle-timeout: 10000
      minimum-idle: 1
      maximum-poll-size: 5
      pool-name: pedido-api
---
#jpa
spring:
  jpa:
    hibernate:
      ddl-auto: none # When you launch the application for the first time - switch "none" at "create"
    generate-ddl: ${GENERATE_DDL:true}
    show-sql: ${ENABLE_SQL:true}
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: ${OPEN_IN_VIEW:false}
    database: postgresql
---
# flyway
spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    baseline-version: 1
    sql-migration-prefix: V
    sql-migration-separator: __
    sql-migration-sufix: .sql


---
spring:
  boot:
    admin:
      client:
        enabled: ${SPRING_ADMIN_ACTIVE:false}
        url: ${SPRING_ADMIN_URL:http://localhost:4000}
        instance:
          service-url: ${CLIENT_SERVICE_URL:http://localhost:4004}
          health-url: ${CLIENT_HEALTH_URL:http://localhost:4004/actuator/health}
          management-url: ${CLIENT_MANAGEMENT_URL:http://localhost:4004/actuator}