server:
  port: ${PORT:4000}
spring:
  application:
    name: pedidos
  profiles:
    active: ${PROFILE:dev}
---
# endpoint metrics
management:
  endpoints:
    web:
      exposure:
        include: ${EXPOSURE_INCLUDE:*}


---
#rabbit
spring:
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${HABBIT_PORT:5672}
    username: ${RABBIT_USER:admin}
    password: ${RABBIT_PASSWORD:admin}

---
springdoc:
  api-docs:
    path: /api-docs
  packages-to-scan: com.desafio.pedidos
  swagger-ui:
    enabled: true
    path: /documentation
    tryItOutEnabled: true
    tagsSorter: alpha
    filter: true

---
# endpoint metrics
management:
  endpoints:
    web:
      exposure:
        include: ${EXPOSURE_INCLUDE:health,loggers,prometheus,metrics,info}
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
---
config:
  rabbit-queue-name: ${RABBIT_QUEUE_NAME:pedido-request-queue}
  openapi:
    dev-url: ${OPENAPI_DEV_URL:}
    prod-url: ${OPENAPI_PROD_URL:}
