server:
  port: ${PORT:4000}
spring:
  application:
    name: pedidos
  profiles:
    active: ${PROFILE:test}


---
#rabbit
spring:
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${HABBIT_PORT:5672}
    username: ${RABBIT_USER:admin}
    password: ${RABBIT_PASSWORD:admin}

---
springdoc:
  api-docs:
    path: /api-docs
  packages-to-scan: "com.btg_desafio.pedidos"
  swagger-ui:
    path: /documentation
    tryItOutEnabled: true
    tagsSorter: alpha
    filter: true
---
config:
  openapi:
    dev-url: ${OPENAPI_DEV_URL:}
    prod-url: ${OPENAPI_PROD_URL:}