server:
  port: ${PORT:4000}
spring:
  application:
    name: pedidos
  profiles:
    active: ${PROFILE:test}


---
#rabbit
spring:
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${HABBIT_PORT:5672}
    username: ${RABBIT_USER:admin}
    password: ${RABBIT_PASSWORD:admin}