name: CI-CD

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Teste de Build
        run: mvn --batch-mode --update-snapshots clean package

  CRIAR-NOVA-IMAGEM:
    runs-on: ubuntu-latest
    needs:
      - build-test
    steps:
      - uses: actions/checkout@v3
      - name: Autenticando usuário no docker
        uses: docker/login-action@v2.0.0
        with:
          # Server address of Docker registry. If not set then will default to Docker Hub
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}

      - name: Verificando a definição de GITHUB_REF
        env:
          IMAGE_TAG: "${GITHUB_REF##*/}"
        run: echo "O valor de GITHUB_REF é ${{ env.IMAGE_TAG }} " |
          echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Construindo a imagem e enviando para o DockerHub
        # You may pin to the exact commit or the version.
        # uses: docker/build-push-action@e551b19e49efd4e98792db7592c17c09b89db8d8
        uses: docker/build-push-action@v3.0.0
        with:
          file: ./Dockerfile
          context: ./
          push: true
          tags:  |
            viniciushora/desafio-pedido:latest
            viniciushora/desafio-pedido:${{ env.BRANCH }}

#  ENVIAR-PARA-HEROKU:

